<H1 align='center'>Bug Report Form
<A HREF="/webqtl/main.py?FormID=editHtml"><img src="images/modify.gif" alt="modify this page" border= 0 valign="middle"></A></H1>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 493, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' Table1.Name=Table3.Name , Table2.Name=Table3.Name  GROUP BY Table1.Name) as Com' at line 1")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 493, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' Table1.Name=Table3.Name , Table2.Name=Table3.Name  GROUP BY Table1.Name) as Com' at line 1")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 494, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' Table1.Name=Table3.Name , Table2.Name=Table3.Name  GROUP BY Table1.Name) as Com' at line 1")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 539
     i += 1
     ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 577
     i += 1
     ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 577
     i += 1
     ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 554
     SearchText.append(HT.Italic('match the term '), Id='green'))
                                                                ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 555
     ttext.append(HT.Italic('match the term '), Id='green'))
                                                           ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in __init__
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in <lambda>
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
AttributeError: 'NoneType' object has no attribute 'prefix'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in __init__
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in <lambda>
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
AttributeError: 'NoneType' object has no attribute 'prefix'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in __init__
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in <lambda>
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
AttributeError: 'NoneType' object has no attribute 'prefix'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in __init__
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in <lambda>
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
AttributeError: 'NoneType' object has no attribute 'prefix'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in __init__
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in <lambda>
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
AttributeError: 'NoneType' object has no attribute 'prefix'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in __init__
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
  File "/node_apps/www/cgi-bin/searchPage.py", line 86, in <lambda>
    self.dbPrefix = map(lambda X: X.prefix, self.dbInfos)
AttributeError: 'NoneType' object has no attribute 'prefix'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 493, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY Table1.Name) as CombineTable WHERE ProbeSet.Id = ProbeSetXRef.ProbeSetI' at line 1")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 493, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY Table1.Name) as CombineTable WHERE ProbeSet.Id = ProbeSetXRef.ProbeSetI' at line 1")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 493, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY Table1.Name) as CombineTable WHERE ProbeSet.Id = ProbeSetXRef.ProbeSetI' at line 1")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 493, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY Table1.Name) as CombineTable WHERE ProbeSet.Id = ProbeSetXRef.ProbeSetI' at line 1")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 494, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY Table1.Name) as CombineTable WHERE ProbeSet.Id = ProbeSetXRef.ProbeSetI' at line 1")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 146, in ?
    page3 = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 146, in ?
    page3 = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 146, in ?
    page3 = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 226, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, variance = _vars, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 146, in ?
    page3 = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/cgi-bin/Yanhua/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/Yanhua/dataPage.py", line 930, in __init__
    fd.readGenotype()
  File "/node_apps/www/cgi-bin/Yanhua/DataForm.py", line 132, in readGenotype
    self.genotype_1.read(os.path.join(CONFIG_genodir, self.RISet + '.geno'))
SystemError: The given file doesn't exist

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/dataPage.py", line 882, in __init__
    fd.readGenotype()
  File "/home/hqli/public_html/cgi-bin/beta/DataForm.py", line 131, in readGenotype
    self.genotype_1.read(os.path.join(CONFIG_genodir, self.RISet + '.geno'))
SystemError: The given file doesn't exist

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/cgi-bin/Yanhua/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/Yanhua/dataPage.py", line 930, in __init__
    fd.readGenotype()
  File "/node_apps/www/cgi-bin/Yanhua/DataForm.py", line 132, in readGenotype
    self.genotype_1.read(os.path.join(CONFIG_genodir, self.RISet + '.geno'))
SystemError: The given file doesn't exist

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/cgi-bin/Yanhua/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/Yanhua/dataPage.py", line 930, in __init__
    fd.readGenotype()
  File "/node_apps/www/cgi-bin/Yanhua/DataForm.py", line 132, in readGenotype
    self.genotype_1.read(os.path.join(CONFIG_genodir, self.RISet + '.geno'))
SystemError: The given file doesn't exist

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 33, in ?
    fd = FormData(formdata)
  File "/node_apps/www/cgi-bin/DataForm.py", line 99, in __init__
    f1, self.mpolar, self.ppolar = ParInfo[self.RISet]
KeyError: 'BDF2-2005'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 33, in ?
    fd = FormData(formdata)
  File "/node_apps/www/cgi-bin/DataForm.py", line 99, in __init__
    f1, self.mpolar, self.ppolar = ParInfo[self.RISet]
KeyError: 'BDF2-2005'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/dataPage.py", line 882, in __init__
    fd.readGenotype()
  File "/home/hqli/public_html/cgi-bin/beta/DataForm.py", line 131, in readGenotype
    self.genotype_1.read(os.path.join(CONFIG_genodir, self.RISet + '.geno'))
SystemError: The given file doesn't exist

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 495
     print item, <BR>
                 ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2815, in __init__
    LRSResult = _genotype.regression(_strains, _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 146, in ?
    page3 = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 136, in ?
    page = editHtmlPage(fd)
  File "/node_apps/www/cgi-bin/upddataPage.py", line 1060, in __init__
    fp = open(fileName, 'wb')
IOError: [Errno 2] No such file or directory: '/node_apps/www/html/webqtl//webqtl/main.py'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2815, in __init__
    LRSResult = _genotype.regression(_strains, _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/beta/intervalPage.py", line 2815, in __init__
    LRSResult = _genotype.regression(_strains, _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 146, in ?
    page3 = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 146, in ?
    page3 = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2815, in __init__
    LRSResult = _genotype.regression(_strains, _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
NameError: name 'MultipleIntMappingPage' is not defined

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 435, in __init__
    self.cursor.execute(item)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1139, "Got error 'parentheses not balanced' from regexp")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 73, in ?
    page = ResultsPage(fd)
  File "/node_apps/www/cgi-bin/resultPage.py", line 153, in __init__
    resultstable = self.GenReport(fd, _genotype, _strains, _vals, _vars)
  File "/node_apps/www/cgi-bin/resultPage.py", line 163, in GenReport
    qtlresults = _genotype.regression(strains = _strains, trait = _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 73, in ?
    page = ResultsPage(fd)
  File "/node_apps/www/cgi-bin/resultPage.py", line 153, in __init__
    resultstable = self.GenReport(fd, _genotype, _strains, _vals, _vars)
  File "/node_apps/www/cgi-bin/resultPage.py", line 163, in GenReport
    qtlresults = _genotype.regression(strains = _strains, trait = _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 140, in ?
    page2 = CorrelationPage(fd)
  File "/node_apps/www/cgi-bin/correlationPage.py", line 116, in __init__
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'db_webqtl.ProbeSetXRef' doesn't exist")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 140, in ?
    page2 = CorrelationPage(fd)
  File "/node_apps/www/cgi-bin/correlationPage.py", line 116, in __init__
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'db_webqtl.ProbeSetXRef' doesn't exist")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 124, in ?
    page=CorrelationPage(fd)
  File "/node_apps/www/cgi-bin/correlationPage.py", line 116, in __init__
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'db_webqtl.ProbeSetXRef' doesn't exist")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 124, in ?
    page=CorrelationPage(fd)
  File "/node_apps/www/cgi-bin/correlationPage.py", line 116, in __init__
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1017, "Can't find file: './db_webqtl/ProbeSetXRef.frm' (errno: 13)")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2815, in __init__
    LRSResult = _genotype.regression(_strains, _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 146, in ?
    page3 = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2815, in __init__
    LRSResult = _genotype.regression(_strains, _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2815, in __init__
    LRSResult = _genotype.regression(_strains, _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16
     thekeys = fd.keys
           ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16
     for key in fd.keys:
       ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16
     for akey in fd.formdata.keys:
       ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 17
     print fd.formdata.keys
         ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 17
     print 'fd.formdata.keys'
         ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 160, in ?
    from searchPage import *
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16
     self.database = fd.formdata.getvalue('database', '')
        ^
 SyntaxError: invalid syntax

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16, in __init__
    print fd.formdata.keys.length
AttributeError: 'function' object has no attribute 'length'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16, in __init__
    print length(fd.formdata.keys)
NameError: global name 'length' is not defined

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16, in __init__
    print len(fd.formdata.keys)
TypeError: len() of unsized object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16, in __init__
    print len(fd.formdata.list())
TypeError: 'list' object is not callable

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16, in __init__
    print len(fd.formdata.getlist())
TypeError: getlist() takes exactly 2 arguments (1 given)

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 16, in __init__
    print fd.formdata.getkeys()
  File "/usr/src/build/475206-i386/install/usr/lib/python2.3/cgi.py", line 533, in __getattr__
    raise AttributeError, name
AttributeError: getkeys

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 18, in __init__
    print fd.formdata.getValue('database')
  File "/usr/src/build/475206-i386/install/usr/lib/python2.3/cgi.py", line 533, in __getattr__
    raise AttributeError, name
AttributeError: getValue

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 945, in __init__
    nstrains = [[None]] * len(traitdata)
TypeError: len() of unsized object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 872, in __init__
    fd.RISet = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 872, in __init__
    fd.RISet = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 872, in __init__
    fd.RISet = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 872, in __init__
    fd.RISet = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 872, in __init__
    fd.RISet = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 872, in __init__
    fd.RISet = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 872, in __init__
    fd.RISet = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 170, in ?
    page = ShowDatabasePage(fd)
  File "/node_apps/www/cgi-bin/dataPage.py", line 872, in __init__
    fd.RISet = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 77, in __init__
    self.databaseCrosses, self.databaseCrossIds= self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 566, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 303, in ?
    page = cmdCorrelation(fd)
  File "/node_apps/www/cgi-bin/TextUI.py", line 433, in __init__
    self.readDB()
  File "/node_apps/www/cgi-bin/TextUI.py", line 555, in readDB
    self.cursor.execute(query)
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'LocusID' in 'field list'")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 112, in ?
    page = ClusterTreePage(fd)
  File "/node_apps/www/cgi-bin/correlationPage.py", line 1148, in __init__
    qtlresult = fd.genotype.regression(strains = _strains, trait = _vals)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 228, in __init__
    LRSArray = _genotype.permutation(strains = _strains, trait = _vals, nperm=fd.nperm)
IndexError: the length of the strain list and the value list are different, 
or they are less than 8 

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 358, in __init__
    gifmap = self.plotIntMapping(intCanvas, _LRSResult, _bootResult, fd, offset = (75, 120, 80, 10))
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2374, in plotIntMapping
    additiveStep = (additiveScale[1]-additiveScale[0])/additiveScale[2]
TypeError: unsubscriptable object

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 136, in ?
    page = editHtmlPage(fd)
  File "/node_apps/www/cgi-bin/upddataPage.py", line 1060, in __init__
    fp = open(fileName, 'wb')
IOError: [Errno 13] Permission denied: '/node_apps/www/html/webqtl//dbdoc/HC_M2_1005_P.html'

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 56, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 56, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 56, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 56, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 56, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 56, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 57, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/home/hqli/public_html/cgi-bin/beta/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/home/hqli/public_html/cgi-bin/beta/searchPage.py", line 57, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "/node_apps/www/webqtl/main.py", line 162, in ?
    page = SearchResultPage(fd)
  File "/node_apps/www/cgi-bin/searchPage.py", line 56, in __init__
    indId, indName, indFullName, indConfid = self.cursor.fetchall()[0]
IndexError: tuple index out of range

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 519, in __init__
    mainAreas = self.plotIntMappingALEX_TEST(intCanvas, _LRSResult, _bootResult, fd, geneTable=geneTableMain, offset= (self.WIDTH_LEFT_OFFSET_DEFAULT, self.WIDTH_RIGHT_OFFSET_DEFAULT, self.HEIGHT_TOP_OFFSET_DEFAULT, self.HEIGHT_BOTTOM_OFFSET_DEFAULT), zoom = 1)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 1786, in plotIntMappingALEX_TEST
    geneCol.loadGenesOnChr(chrName, self.cursor, self.diffCol, self.startMb, self.endMb, fd.identification)
  File "/node_apps/www/cgi-bin/GeneCollection.py", line 88, in loadGenesOnChr
    cursor.execute("SELECT count(id) FROM SNP_perlegen where mb > %f and mb < %f and chr = '%s' and %s=1" % (gene[4]-0.002, gene[5]+0.002, tempChr, diffCol))
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'db_webqtl.SNP_perlegen' doesn't exist")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 519, in __init__
    mainAreas = self.plotIntMappingALEX_TEST(intCanvas, _LRSResult, _bootResult, fd, geneTable=geneTableMain, offset= (self.WIDTH_LEFT_OFFSET_DEFAULT, self.WIDTH_RIGHT_OFFSET_DEFAULT, self.HEIGHT_TOP_OFFSET_DEFAULT, self.HEIGHT_BOTTOM_OFFSET_DEFAULT), zoom = 1)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 1786, in plotIntMappingALEX_TEST
    geneCol.loadGenesOnChr(chrName, self.cursor, self.diffCol, self.startMb, self.endMb, fd.identification)
  File "/node_apps/www/cgi-bin/GeneCollection.py", line 88, in loadGenesOnChr
    cursor.execute("SELECT count(id) FROM SNP_perlegen where mb > %f and mb < %f and chr = '%s' and %s=1" % (gene[4]-0.002, gene[5]+0.002, tempChr, diffCol))
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'db_webqtl.SNP_perlegen' doesn't exist")

</pre>
<P><HR><P>

<H2>Bug Report</H2><BR><pre>Traceback (most recent call last):
  File "./cmdLine.py", line 120, in ?
    page = MultipleIntMappingPage(fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 2733, in __init__
    IntMappingPage.__init__(self,fd)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 519, in __init__
    mainAreas = self.plotIntMappingALEX_TEST(intCanvas, _LRSResult, _bootResult, fd, geneTable=geneTableMain, offset= (self.WIDTH_LEFT_OFFSET_DEFAULT, self.WIDTH_RIGHT_OFFSET_DEFAULT, self.HEIGHT_TOP_OFFSET_DEFAULT, self.HEIGHT_BOTTOM_OFFSET_DEFAULT), zoom = 1)
  File "/node_apps/www/cgi-bin/intervalPage.py", line 1786, in plotIntMappingALEX_TEST
    geneCol.loadGenesOnChr(chrName, self.cursor, self.diffCol, self.startMb, self.endMb, fd.identification)
  File "/node_apps/www/cgi-bin/GeneCollection.py", line 88, in loadGenesOnChr
    cursor.execute("SELECT count(id) FROM SNP_perlegen where mb > %f and mb < %f and chr = '%s' and %s=1" % (gene[4]-0.002, gene[5]+0.002, tempChr, diffCol))
  File "/usr/lib/python2.3/site-packages/MySQLdb/cursors.py", line 137, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.3/site-packages/MySQLdb/connections.py", line 33, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'db_webqtl.SNP_perlegen' doesn't exist")

</pre>
<P><HR><P>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-3782271-1";
urchinTracker();
</script>
